### ISSUE TITLE
Compilation failed on 2.5.0 version

### ISSUE THREAD

**Issue by miborra** [springfox/springfox#1384]
I create a fork from 2.5.0 version. When I try to compile with gradle 2.1.4 I get these errors:

```
springfox.gradlebuild.version.SemanticVersionTest > initializationError FAILED
    java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing

        Caused by:
        java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing

springfox.gradlebuild.version.GitVersionParserSpec > initializationError FAILED
    java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing

        Caused by:
        java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing

```

What can I do to solve this problem?

**Comment by dilipkrish** [comment]
Please use the gradle wrapper 

```bash
./gradlew clean build
```

**Comment by miborra** [comment]
Thanks!
This solved my problem
