### ISSUE TITLE
springfox doesn't work with spring boot 2.0 and spring data Kay-RC2

### ISSUE THREAD

**Issue by shashankitmaster** [springfox/springfox#1957]
- What version of the library are you using
I am using latest released version: 2.7.0

What kind of issue is this?
- [x] Feature Request:- Springfox support for spring-data-rest covered inside spring data KAY-RC2

When I am using Springfox with Spring-boot 2.0.0.M3 and Spring Data release train KAY-RC2, it is showing me the error like below:

```java
Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;
	at springfox.documentation.spring.data.rest.EntityServicesProvider.requestHandlers(EntityServicesProvider.java:81) ~[springfox-data-rest-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:129) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:126) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799) ~[guava-18.0.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-18.0.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-18.0.jar:na]
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548) ~[guava-18.0.jar:na]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300) ~[guava-18.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691) ~[guava-18.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275) ~[guava-18.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226) ~[guava-18.0.jar:na]
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:373) ~[guava-18.0.jar:na]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:100) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:91) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:183) ~[spring-context-5.0.0.RC3.jar:5.0.0.RC3]
```
Thanks.

**Comment by sangtraceur** [comment]
Confirmed. Facing the same issue, after including springfox support for datarest.

**Comment by zzFluke** [comment]
Same here. Here are runtime dependencies:

+--- org.springframework.boot:spring-boot-starter-data-jpa: -> 2.0.0.M3
|    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3
|    |    +--- org.springframework.boot:spring-boot:2.0.0.M3
|    |    |    +--- org.springframework:spring-core:5.0.0.RC3
|    |    |    |    \--- org.springframework:spring-jcl:5.0.0.RC3
|    |    |    \--- org.springframework:spring-context:5.0.0.RC3
|    |    |         +--- org.springframework:spring-aop:5.0.0.RC3
|    |    |         |    +--- org.springframework:spring-beans:5.0.0.RC3
|    |    |         |    |    \--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    |         |    \--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    |         +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |    |         +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    |         \--- org.springframework:spring-expression:5.0.0.RC3
|    |    |              \--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.0.0.M3
|    |    |    \--- org.springframework.boot:spring-boot:2.0.0.M3 (*)
|    |    +--- org.springframework.boot:spring-boot-starter-logging:2.0.0.M3
|    |    |    +--- ch.qos.logback:logback-classic:1.2.3
|    |    |    |    +--- ch.qos.logback:logback-core:1.2.3
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    |    +--- org.slf4j:jul-to-slf4j:1.7.25
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    |    \--- org.slf4j:log4j-over-slf4j:1.7.25
|    |    |         \--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    \--- org.yaml:snakeyaml:1.18
|    +--- org.springframework.boot:spring-boot-starter-aop:2.0.0.M3
|    |    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    |    +--- org.springframework:spring-aop:5.0.0.RC3 (*)
|    |    \--- org.aspectj:aspectjweaver:1.8.10
|    +--- org.springframework.boot:spring-boot-starter-jdbc:2.0.0.M3
|    |    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    |    +--- com.zaxxer:HikariCP:2.6.3
|    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    \--- org.springframework:spring-jdbc:5.0.0.RC3
|    |         +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |         +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |         \--- org.springframework:spring-tx:5.0.0.RC3
|    |              +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |              \--- org.springframework:spring-core:5.0.0.RC3 (*)
|    +--- org.hibernate:hibernate-core:5.2.10.Final
|    |    +--- org.jboss.logging:jboss-logging:3.3.0.Final -> 3.3.1.Final
|    |    +--- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final
|    |    +--- org.javassist:javassist:3.20.0-GA -> 3.21.0-GA
|    |    +--- antlr:antlr:2.7.7
|    |    +--- org.jboss:jandex:2.0.3.Final
|    |    +--- com.fasterxml:classmate:1.3.0 -> 1.3.3
|    |    +--- dom4j:dom4j:1.6.1
|    |    \--- org.hibernate.common:hibernate-commons-annotations:5.0.1.Final
|    |         \--- org.jboss.logging:jboss-logging:3.3.0.Final -> 3.3.1.Final
|    +--- javax.transaction:javax.transaction-api:1.2
|    +--- org.springframework.data:spring-data-jpa:2.0.0.RC2
|    |    +--- org.springframework.data:spring-data-commons:2.0.0.RC2
|    |    |    +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    |    +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.springframework:spring-orm:5.0.0.RC3
|    |    |    +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |    |    +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    |    +--- org.springframework:spring-jdbc:5.0.0.RC3 (*)
|    |    |    \--- org.springframework:spring-tx:5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-context:5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-aop:5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-tx:5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    \--- org.slf4j:slf4j-api:1.7.25
|    \--- org.springframework:spring-aspects:5.0.0.RC3
|         \--- org.aspectj:aspectjweaver:1.9.0.BETA-6 -> 1.8.10
**+--- org.springframework.boot:spring-boot-starter-data-rest: -> 2.0.0.M3**
|    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    +--- org.springframework.boot:spring-boot-starter-json:2.0.0.M3
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0.pr4
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.0.pr4
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.0.pr4
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.0.pr4
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.0.pr4
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0.pr4
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.0.pr4
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|    |    +--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.9.0.pr4
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.0.pr4
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|    |    \--- com.fasterxml.jackson.module:jackson-module-kotlin:2.9.0.pr4
|    |         +--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|    |         \--- com.fasterxml.jackson.core:jackson-annotations:2.9.0.pr4
|    +--- org.springframework.boot:spring-boot-starter-web:2.0.0.M3
|    |    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    |    +--- org.springframework.boot:spring-boot-starter-json:2.0.0.M3 (*)
|    |    +--- org.springframework.boot:spring-boot-starter-tomcat:2.0.0.M3
|    |    |    +--- org.apache.tomcat.embed:tomcat-embed-core:8.5.16
|    |    |    +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.16
|    |    |    \--- org.apache.tomcat.embed:tomcat-embed-websocket:8.5.16
|    |    |         \--- org.apache.tomcat.embed:tomcat-embed-core:8.5.16
|    |    +--- org.hibernate:hibernate-validator:5.4.1.Final
|    |    |    +--- javax.validation:validation-api:1.1.0.Final
|    |    |    +--- org.jboss.logging:jboss-logging:3.3.0.Final -> 3.3.1.Final
|    |    |    \--- com.fasterxml:classmate:1.3.1 -> 1.3.3
|    |    +--- org.springframework:spring-web:5.0.0.RC3
|    |    |    +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |    |    \--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |    \--- org.springframework:spring-webmvc:5.0.0.RC3
|    |         +--- org.springframework:spring-aop:5.0.0.RC3 (*)
|    |         +--- org.springframework:spring-beans:5.0.0.RC3 (*)
|    |         +--- org.springframework:spring-context:5.0.0.RC3 (*)
|    |         +--- org.springframework:spring-core:5.0.0.RC3 (*)
|    |         +--- org.springframework:spring-expression:5.0.0.RC3 (*)
|    |         \--- org.springframework:spring-web:5.0.0.RC3 (*)
|    \--- org.springframework.data:spring-data-rest-webmvc:3.0.0.RC2
|         **+--- org.springframework.data:spring-data-rest-core:3.0.0.RC2**
|         |    +--- org.springframework:spring-tx:5.0.0.RC3 (*)
|         |    +--- org.springframework.hateoas:spring-hateoas:0.23.0.RELEASE
|         |    |    +--- org.springframework:spring-aop:4.3.5.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-beans:4.3.5.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-context:4.3.5.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-core:4.3.5.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-web:4.3.5.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-webmvc:4.3.5.RELEASE -> 5.0.0.RC3 (*)
|         |    |    \--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|         |    +--- org.springframework.data:spring-data-commons:2.0.0.RC2 (*)
|         |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE
|         |    |    +--- org.springframework:spring-beans:4.0.9.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-context:4.0.9.RELEASE -> 5.0.0.RC3 (*)
|         |    |    +--- org.springframework:spring-aop:4.0.9.RELEASE -> 5.0.0.RC3 (*)
|         |    |    \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
|         |    +--- org.atteo:evo-inflector:1.2.2
|         |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0.pr4
|         |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.0.pr4 (*)
|         |    \--- org.slf4j:slf4j-api:1.7.25
|         +--- org.springframework:spring-webmvc:5.0.0.RC3 (*)
|         +--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0.pr4
|         \--- org.slf4j:slf4j-api:1.7.25
+--- org.springframework.boot:spring-boot-starter-jooq: -> 2.0.0.M3
|    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    +--- org.springframework.boot:spring-boot-starter-jdbc:2.0.0.M3 (*)
|    +--- org.springframework:spring-tx:5.0.0.RC3 (*)
|    \--- org.jooq:jooq:3.9.4
+--- org.springframework.boot:spring-boot-starter-jersey: -> 2.0.0.M3
|    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    +--- org.springframework.boot:spring-boot-starter-json:2.0.0.M3 (*)
|    +--- org.springframework.boot:spring-boot-starter-tomcat:2.0.0.M3 (*)
|    +--- org.springframework.boot:spring-boot-starter-validation:2.0.0.M3
|    |    +--- org.springframework.boot:spring-boot-starter:2.0.0.M3 (*)
|    |    +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.16
|    |    \--- org.hibernate:hibernate-validator:5.4.1.Final (*)
|    +--- org.springframework:spring-web:5.0.0.RC3 (*)
|    +--- org.glassfish.jersey.core:jersey-server:2.25.1
|    |    +--- org.glassfish.jersey.core:jersey-common:2.25.1
|    |    |    +--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    |    |    +--- javax.annotation:javax.annotation-api:1.2
|    |    |    +--- org.glassfish.jersey.bundles.repackaged:jersey-guava:2.25.1
|    |    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32
|    |    |    |    +--- org.glassfish.hk2:hk2-utils:2.5.0-b32
|    |    |    |    \--- org.glassfish.hk2.external:aopalliance-repackaged:2.5.0-b32
|    |    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    |    +--- org.glassfish.hk2:hk2-locator:2.5.0-b32
|    |    |    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    |    |    +--- org.glassfish.hk2.external:aopalliance-repackaged:2.5.0-b32
|    |    |    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32 (*)
|    |    |    |    +--- org.glassfish.hk2:hk2-utils:2.5.0-b32
|    |    |    |    \--- org.javassist:javassist:3.20.0-GA -> 3.21.0-GA
|    |    |    \--- org.glassfish.hk2:osgi-resource-locator:1.0.1
|    |    +--- org.glassfish.jersey.core:jersey-client:2.25.1
|    |    |    +--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    |    |    +--- org.glassfish.jersey.core:jersey-common:2.25.1 (*)
|    |    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32 (*)
|    |    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    |    \--- org.glassfish.hk2:hk2-locator:2.5.0-b32 (*)
|    |    +--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    |    +--- org.glassfish.jersey.media:jersey-media-jaxb:2.25.1
|    |    |    +--- org.glassfish.jersey.core:jersey-common:2.25.1 (*)
|    |    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32 (*)
|    |    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    |    +--- org.glassfish.hk2:hk2-locator:2.5.0-b32 (*)
|    |    |    \--- org.glassfish.hk2:osgi-resource-locator:1.0.1
|    |    +--- javax.annotation:javax.annotation-api:1.2
|    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32 (*)
|    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    +--- org.glassfish.hk2:hk2-locator:2.5.0-b32 (*)
|    |    \--- javax.validation:validation-api:1.1.0.Final
|    +--- org.glassfish.jersey.containers:jersey-container-servlet-core:2.25.1
|    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    +--- org.glassfish.jersey.core:jersey-common:2.25.1 (*)
|    |    +--- org.glassfish.jersey.core:jersey-server:2.25.1 (*)
|    |    \--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    +--- org.glassfish.jersey.containers:jersey-container-servlet:2.25.1
|    |    +--- org.glassfish.jersey.containers:jersey-container-servlet-core:2.25.1 (*)
|    |    +--- org.glassfish.jersey.core:jersey-common:2.25.1 (*)
|    |    +--- org.glassfish.jersey.core:jersey-server:2.25.1 (*)
|    |    \--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    +--- org.glassfish.jersey.ext:jersey-bean-validation:2.25.1
|    |    +--- org.glassfish.hk2.external:javax.inject:2.5.0-b32
|    |    +--- org.glassfish.jersey.core:jersey-common:2.25.1 (*)
|    |    +--- org.glassfish.jersey.core:jersey-server:2.25.1 (*)
|    |    +--- javax.validation:validation-api:1.1.0.Final
|    |    +--- org.hibernate:hibernate-validator:5.1.3.Final -> 5.4.1.Final (*)
|    |    \--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    +--- org.glassfish.jersey.ext:jersey-spring3:2.25.1
|    |    +--- org.glassfish.jersey.core:jersey-server:2.25.1 (*)
|    |    +--- org.glassfish.jersey.containers:jersey-container-servlet-core:2.25.1 (*)
|    |    +--- org.glassfish.hk2:hk2:2.5.0-b32
|    |    |    +--- org.glassfish.hk2:hk2-utils:2.5.0-b32
|    |    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32 (*)
|    |    |    +--- org.glassfish.hk2:config-types:2.5.0-b32
|    |    |    |    \--- org.glassfish.hk2:hk2-config:2.5.0-b32
|    |    |    |         +--- org.glassfish.hk2:hk2-core:2.5.0-b32
|    |    |    |         |    +--- org.glassfish.hk2:hk2-locator:2.5.0-b32 (*)
|    |    |    |         |    \--- org.glassfish.hk2:hk2-utils:2.5.0-b32
|    |    |    |         \--- org.hibernate:hibernate-validator:5.2.4.Final -> 5.4.1.Final (*)
|    |    |    +--- org.glassfish.hk2:hk2-core:2.5.0-b32 (*)
|    |    |    +--- org.glassfish.hk2:hk2-config:2.5.0-b32 (*)
|    |    |    +--- org.glassfish.hk2:hk2-locator:2.5.0-b32 (*)
|    |    |    +--- org.glassfish.hk2:hk2-runlevel:2.5.0-b32
|    |    |    |    +--- org.glassfish.hk2:hk2-api:2.5.0-b32 (*)
|    |    |    |    \--- org.glassfish.hk2:hk2-locator:2.5.0-b32 (*)
|    |    |    \--- org.glassfish.hk2:class-model:2.5.0-b32
|    |    |         \--- org.glassfish.hk2.external:asm-all-repackaged:2.5.0-b32
|    |    +--- org.glassfish.hk2:spring-bridge:2.5.0-b32
|    |    |    \--- org.springframework:spring-context:3.2.3.RELEASE -> 5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-beans:3.2.17.RELEASE -> 5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-core:3.2.17.RELEASE -> 5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-web:3.2.17.RELEASE -> 5.0.0.RC3 (*)
|    |    +--- org.springframework:spring-aop:3.2.17.RELEASE -> 5.0.0.RC3 (*)
|    |    \--- javax.ws.rs:javax.ws.rs-api:2.0.1
|    \--- org.glassfish.jersey.media:jersey-media-json-jackson:2.25.1
|         +--- org.glassfish.jersey.core:jersey-common:2.25.1 (*)
|         +--- org.glassfish.jersey.ext:jersey-entity-filtering:2.25.1
|         |    \--- javax.ws.rs:javax.ws.rs-api:2.0.1
|         +--- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.8.4 -> 2.9.0.pr4
|         |    +--- com.fasterxml.jackson.core:jackson-core:2.9.0.pr4
|         |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|         +--- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.8.4 -> 2.9.0.pr4
|         |    +--- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.9.0.pr4 (*)
|         |    \--- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.9.0.pr4
|         |         +--- com.fasterxml.jackson.core:jackson-core:2.9.0.pr4
|         |         +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0.pr4
|         |         \--- com.fasterxml.jackson.core:jackson-databind:2.9.0.pr4 (*)
|         \--- com.fasterxml.jackson.core:jackson-annotations:2.8.4 -> 2.9.0.pr4
+--- org.springframework.boot:spring-boot-starter-web: -> 2.0.0.M3 (*)
+--- com.h2database:h2: -> 1.4.196
+--- org.apache.shiro:shiro-core:1.3.2
|    +--- org.slf4j:slf4j-api:1.6.4 -> 1.7.25
|    \--- commons-beanutils:commons-beanutils:1.8.3 -> 1.9.3
|         \--- commons-collections:commons-collections:3.2.2
+--- org.apache.shiro:shiro-web:1.3.2
|    \--- org.apache.shiro:shiro-core:1.3.2 (*)
+--- org.apache.shiro:shiro-spring:1.3.2
|    +--- org.apache.shiro:shiro-core:1.3.2 (*)
|    \--- org.apache.shiro:shiro-web:1.3.2 (*)
+--- io.springfox:springfox-swagger2:2.7.0
|    +--- io.swagger:swagger-annotations:1.5.13
|    +--- io.swagger:swagger-models:1.5.13
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.5 -> 2.9.0.pr4
|    |    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|    |    \--- io.swagger:swagger-annotations:1.5.13
|    +--- io.springfox:springfox-spi:2.7.0
|    |    \--- io.springfox:springfox-core:2.7.0
|    |         +--- net.bytebuddy:byte-buddy:1.6.14
|    |         +--- com.google.guava:guava:18.0 -> 20.0
|    |         +--- com.fasterxml:classmate:1.3.3
|    |         +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |         +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |         \--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE
|    |              +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |              \--- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
|    +--- io.springfox:springfox-schema:2.7.0
|    |    +--- io.springfox:springfox-core:2.7.0 (*)
|    |    \--- io.springfox:springfox-spi:2.7.0 (*)
|    +--- io.springfox:springfox-swagger-common:2.7.0
|    |    +--- io.swagger:swagger-annotations:1.5.13
|    |    +--- io.swagger:swagger-models:1.5.13 (*)
|    |    +--- io.springfox:springfox-spi:2.7.0 (*)
|    |    +--- io.springfox:springfox-schema:2.7.0 (*)
|    |    +--- io.springfox:springfox-spring-web:2.7.0
|    |    |    +--- org.reflections:reflections:0.9.11
|    |    |    |    +--- com.google.guava:guava:20.0
|    |    |    |    \--- org.javassist:javassist:3.21.0-GA
|    |    |    +--- com.google.guava:guava:18.0 -> 20.0
|    |    |    +--- com.fasterxml:classmate:1.3.3
|    |    |    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    |    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    |    |    \--- io.springfox:springfox-spi:2.7.0 (*)
|    |    +--- com.google.guava:guava:18.0 -> 20.0
|    |    +--- com.fasterxml:classmate:1.3.3
|    |    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    |    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    |    \--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    +--- io.springfox:springfox-spring-web:2.7.0 (*)
|    +--- com.google.guava:guava:18.0 -> 20.0
|    +--- com.fasterxml:classmate:1.3.3
|    +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
|    +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
|    +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
|    \--- org.mapstruct:mapstruct:1.1.0.Final
+--- io.springfox:springfox-swagger-ui:2.7.0
|    \--- io.springfox:springfox-spring-web:2.7.0 (*)
**\--- io.springfox:springfox-data-rest:2.7.0**
     +--- com.google.guava:guava:18.0 -> 20.0
     +--- com.fasterxml:classmate:1.3.3
     +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
     +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE (*)
     +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE (*)
     +--- io.springfox:springfox-spi:2.7.0 (*)
     +--- io.springfox:springfox-spring-web:2.7.0 (*)
     +--- org.springframework.data:spring-data-rest-webmvc:2.6.3.RELEASE -> 3.0.0.RC2 (*)
     \--- org.springframework.hateoas:spring-hateoas:0.23.0.RELEASE (*)

**Comment by dilipkrish** [comment]
@kuzuha thats helpful thanks for researching the issue. 🤘

**Comment by predrag-viceic** [comment]
Hello,

I have the same problem with Spring Boot 2.0.0.BUILD-SNAPSHOT.

Is this something that can be fixed soon ? 

Thanks!

**Comment by snwiem** [comment]
Confirmed with spring boot 2.0.0.M3 and springfox 2.7.0 as well.

**Comment by ffazzini** [comment]
I have got the same problem here with spring boot 2.0.0.M5 and springfox 2.7.0

**Comment by dilipkrish** [comment]
Closing as a duplicate. This issue is not fixed.

**Comment by JeromeRaghunandan** [comment]
I have the same issue with spring boot 2.0.0.RELEASE and springfox 2.8.0

`Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;
        at springfox.documentation.spring.data.rest.EntityServicesProvider.requestHandlers(EntityServicesProvider.java:81)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:133)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:130)
        at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:52)
        at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:408)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
        at com.google.common.collect.FluentIterable.toList(FluentIterable.java:614)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:104)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:91)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:158)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
        ... 20 more`

**Comment by karthikbingi666** [comment]
Spring boot 2.0 issue still facing

Error is below

Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;


Anyhelp ?

**Comment by mrkk** [comment]
has been a year, is anyone fixing this please?

**Comment by dilipkrish** [comment]
@mrkk Would you mind trying the latest SNAPSHOT? Its been fixed but not yet released

**Comment by k9m** [comment]
Hi, anyone planning to put this into the next release as we are also having troubles with this?

**Comment by k9m** [comment]
> @mrkk Would you mind trying the latest SNAPSHOT? Its been fixed but not yet released

Would it be possible to release a hotfix for this for Swagger 2.9.x?

**Comment by Masterxilo** [comment]
Same problem with spring boot 2.1.0 or 2.0.5 and springfox/swagger 2.9.2

**Comment by amoraes** [comment]
Any plans to release a hotfix?
