### ISSUE TITLE
Springfox won't work with Springframework 3.2.8 (Spring MVC) and maven

### ISSUE THREAD

**Issue by prizeGit** [springfox/springfox#938]
Struggling to get springfox to work with Spring 3 Here is the setup:

The error is: NoClassDefFoundError: org/springframework/core/DefaultParameterNameDiscoverer

DefaultParameterNameDiscoverer is a Spring 4 class

looking at the dependcy tree ````mvn dependency:tree````
shows a transitive dependency on Spring 4.

Also examining any of the springfox poms 1.0.0 - 2.2.2 shows a dependency on Spring 4.

Will this work with Spring 3 or am I wasting my time

````
com.acme:swagger-demo-service:war:0.0.1-SNAPSHOT
+- io.springfox:springfox-swagger2:jar:2.2.2:compile
|  +- org.mapstruct:mapstruct:jar:1.0.0.CR1:compile
|  +- io.swagger:swagger-annotations:jar:1.5.3:compile
|  +- io.swagger:swagger-models:jar:1.5.3:compile
|  +- io.springfox:springfox-spi:jar:2.2.2:compile
|  |  \- io.springfox:springfox-core:jar:2.2.2:compile
|  +- io.springfox:springfox-schema:jar:2.2.2:compile
|  +- io.springfox:springfox-swagger-common:jar:2.2.2:compile
|  +- io.springfox:springfox-spring-web:jar:2.2.2:compile
|  +- com.google.guava:guava:jar:18.0:compile
|  +- com.fasterxml:classmate:jar:1.2.0:compile
|  +- org.aspectj:aspectjrt:jar:1.8.6:compile
|  +- org.aspectj:aspectjweaver:jar:1.8.6:compile
|  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
|  |  \- org.springframework:spring-aop:jar:4.0.9.RELEASE:compile
|  |     \- aopalliance:aopalliance:jar:1.0:compile
|  +- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
|  \- org.springframework.hateoas:spring-hateoas:jar:0.18.0.RELEASE:compile
+- javax.servlet:servlet-api:jar:2.5:provided
+- com.acme:swagger-demo-common:jar:0.0.1-SNAPSHOT:compile
|  +- com.fasterxml.jackson.core:jackson-core:jar:2.1.5:compile
|  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
|  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
|  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.1.5:compile
|  \- com.fasterxml.jackson.core:jackson-databind:jar:2.1.5:compile
+- junit:junit:jar:4.11:test
|  \- org.hamcrest:hamcrest-core:jar:1.3:test
+- org.slf4j:slf4j-api:jar:1.7.12:compile
+- org.slf4j:slf4j-log4j12:jar:1.7.12:compile
|  \- log4j:log4j:jar:1.2.17:compile
+- org.springframework:spring-core:jar:3.2.8.RELEASE:compile
|  \- commons-logging:commons-logging:jar:1.1.3:compile
+- org.springframework:spring-beans:jar:3.2.8.RELEASE:compile
+- org.springframework:spring-webmvc:jar:3.2.8.RELEASE:compile
|  +- org.springframework:spring-context:jar:3.2.8.RELEASE:compile
|  +- org.springframework:spring-expression:jar:3.2.8.RELEASE:compile
|  \- org.springframework:spring-web:jar:3.2.8.RELEASE:compile
\- org.springframework:spring-test:jar:3.2.8.RELEASE:test
````

Below is my setup:

Maven
```xml

<pom>

    ...
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.compiler.level>1.6</java.compiler.level>
		<spring.version>3.2.8.RELEASE</spring.version>		
	</properties>

    ...
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.2.2</version>
		</dependency>

		<!-- Spring -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${spring.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${spring.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>${spring.version}</version>
			<scope>test</scope>
		</dependency>

    ...

</pom>
````

Web.xml

````xml
<web-app>
  <display-name>swagger-demo</display-name>
	<!-- Declare a Spring MVC DispatcherServlet as usual -->
	<servlet>
		<servlet-name>swagger-demo</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextClass</param-name>
			<param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
		</init-param>
		<!-- Again, config locations must consist of one or more comma- or space-delimited 
			and fully-qualified @Configuration classes -->
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>            	
            	swaggerdemo.rest.context.SpringConfig      	
            </param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>swagger-demo</servlet-name>
		<url-pattern>/</url-pattern>
	</servlet-mapping>
	<welcome-file-list>
		<welcome-file />
	</welcome-file-list>  
</web-app>

````

Java Class

```java
@Configuration
@EnableWebMvc
@ComponentScan(basePackageClasses = DemoPocController.class)
@Import(SwaggerConfiguration.class)
public class SpringConfig extends WebMvcConfigurerAdapter {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}


@Configuration
@EnableSwagger2
public class SwaggerConfiguration {

}
````

**Comment by dilipkrish** [comment]
Because of our reliance on spring-plugin

```bash
|  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
|  |  \- org.springframework:spring-aop:jar:4.0.9.RELEASE:compile
|  |     \- aopalliance:aopalliance:jar:1.0:compile
```

I think its safest to assume a dependence on 4.x and u. You might want to try manually using 1.1.0 of the application and see if that works. Unfortunately, its hard to support multiple versions beyond a certain point. I'd love to hear if you've managed to solve the problem

**Comment by dilipkrish** [comment]
This is a duplicate of #927

**Comment by prizeGit** [comment]
Hi,

For now in my demo app I have simply updated the dependency to Spring 4

````xml
<spring.version>4.0.9.RELEASE</spring.version>
````

and included a dependency

````xml
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-swagger-ui</artifactId>
	<version>2.0.2</version>
</dependency>
````

everything simply works.

I will update if I ever get Spring3 working.

Regards

Peter

**Comment by dilipkrish** [comment]
@prizeGit :+1: 

Also FYI the latest version released is **2.2.2**

**Comment by dilipkrish** [comment]
Closing this a duplicate of #921
