### ISSUE TITLE
Swagger-ui cannot be used in 2.8.0

### ISSUE THREAD

**Issue by filiphr** [springfox/springfox#2187]
Upgrading to 2.8.0 renders the swagger-ui useless. With the addition of https://github.com/springfox/springfox/commit/d737c47b6d7e7dfce45603fe1392c01784a341db and #597 the swagger ui is not working at all. I am constantly getting the prompt with the exception: "Unexpected token < in JSON at position 0". However, with the exact same setup and version 2.7.0 everything works correctly.

**Comment by dilipkrish** [comment]
@filiphr so #597 isn't supported regardless of version of swagger-ui. I verified that the [the demos](https://github.com/springfox/springfox-demos) application works perfectly fine. What browser are you using?

**Comment by filiphr** [comment]
I was using the latest Chrome browser. I know that #597 is not supported, maybe what I am seeing is not even related to that. I am going to check more and get back to you. Will try to perform some debugging to see where exactly this comes from. As currently I am getting the prompt constantly.

**Comment by slolo83510** [comment]
I was in 2.7.0 and I jumped to 2.8.0 and I get a "Unexpected token (". It may also be related to this post.

**Comment by hannes-angst** [comment]
http://localhost:9084/swagger-resources/configuration/ui

**Comment by hannes-angst** [comment]
Looks like the save issue handled by https://github.com/springfox/springfox/issues/2191

**Comment by sroach** [comment]
Is it related to fetch api? 

To cause browsers to send a request with credentials included, even for a cross-origin call, add credentials: 'include' to the init object you pass to the fetch() method.

fetch('https://example.com', {
  credentials: 'include'  
})
If you only want to send credentials if the request URL is on the same origin as the calling script, add credentials: 'same-origin'.

// The calling script is on the origin 'https://example.com'

fetch('https://example.com', {
  credentials: 'same-origin'  
})
 
Like this line
const configUIResponse = await fetch(baseUrl + "/swagger-resources/configuration/ui"); 

Would look like

const configUIResponse = await fetch(baseUrl + "/swagger-resources/configuration/ui", {credentials : ‘same-origin’});

**Comment by dilipkrish** [comment]
Looks like there might be an issue under some cases will need to investigate

**Comment by Droom1995** [comment]
Also encountering an issue while updating to 2.8.0, using springfox-swagger-ui and springfox-swagger2.
Possible cause by 
`@ApiModelProperty(notes = "notes")`

```
Caused by: java.lang.RuntimeException: org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception
is com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: io.swagger.annotations.ApiModelPropert
y.allowEmptyValue()Z
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:236)
```

Works fine with 2.7.0

**Comment by dilipkrish** [comment]
@Droom1995 You may not have the correct swagger-core library version. Verify that it matches with undertow is loading

**Comment by dilipkrish** [comment]
@Droom1995 you need to have `io.swagger:swagger-annotations:1.5.11` or higher

**Comment by filiphr** [comment]
@dilipkrish from which issue is this one a duplicate?

**Comment by dilipkrish** [comment]
The `WRAP_ROOT_VALUE` configuration isnt supported and like you pointed out its duplicated in #597.  There was another issue related to the update that was fixed via #2191. Would love your feedback for 2.8.1-SNAPSHOT as Im planning to release it in the next few days

**Comment by satishpatro44** [comment]
In my case, a swagger was opened in browser, somehow it was calling from that browser's opened swagger

I changed port & started it worked
So, remove all swagger url opened in browser
Not may be the case fot others
