### ISSUE TITLE
Unable to upgrade swagger 2.7.0 to swagger 3.0 in Spring application(not boot)

### ISSUE THREAD

**Issue by skabdus** [springfox/springfox#3601]
My project is working fine with swagger2 version 2.7.0.not spring boot(spring mvc only)
Now  I am going to upgrade it 3.0.0 but it's giving plugin errors.

j**ava.lang.nosuchMethodError:org.springframework.plugin.core.pluginRegistry.getPluginFor(Ljava/lang/Object;)Ljava/util/Optional;**

My config as below:

<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>3.0.0</version>
</dependency>

Update: As mentioned in https://github.com/springfox/springfox
Step 2 : Add @EnableOpenApi for open API (and @EnableSwagger2WebMvc or @EnableSwagger2WebFlux for older versions)
I added @EnableSwagger2WebMvc in class ,Then it's asking dependency of springfox-swagger2,
as this coming from :
http://springfox.github.io/springfox/javadoc/snapshot/springfox/documentation/swagger2/annotations/EnableSwagger2WebMvc.html 
which is part of springfox-swagger2 dependency Hence can't delete dependecy as well.

Hence I am confused what to do..
can you please help cleaner approach with steps
