### ISSUE TITLE
Classmate version 1.2.0 inconsistent with spring-boot-starter-web 1.2.5-REALEASE

### ISSUE THREAD

**Issue by dstackowiak** [springfox/springfox#948]
With the 2.2.2 of springfox, specifics class of classmate v1.2.0 is used. 
But spring-boot-starter-web1.2.5-RELEASE has classmate-1.0.0 dependency.
spring-boot-starter-web1.2.5-RELEASE -> hibernate-validator-5.1.3.Final -> classmate-1.0.0

So when i started my app, i have :
```
java.lang.NoClassDefFoundError: com/fasterxml/classmate/members/ResolvedParameterizedMember
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
```

Works fine with with springfox-2.1.2

**Comment by dilipkrish** [comment]
You should be able to use dependency management to ask it to use classmate 1.2.0

**Comment by dstackowiak** [comment]
Thx, indeed, this work when i force classmate-1.2.0 in my project with dependency management :)  

However isn't the most elegant solution. I have many spring-boot project  who use spingfox (more precisely, these project have a dependency to a custom spring-starter for swagger/springfox configuration), so i need to update/maintain all dependency management in these projects.

For information, the current master of spring-boot (1.3.0-SNAPSHOT) use hibernate-validator-5.2.1-FINAL -> classmate-*1.1.0* .
