### ISSUE TITLE
Spring Data Rest Integration doesn't document repository method parameters correctly

### ISSUE THREAD

**Issue by thombergs** [springfox/springfox#1963]
I have just evaluated generating a Swagger Documentation for a Spring Data Rest repository with the Spring Data Rest Integration feature in the current 2.7.0 release and came upon the following bug.

When creating a custom query method in a Spring Data repository like `findByCustomerId()` in the snippet below, Springfox documents the input parameters to that method incorrectly. In the generated documentation the parameter is called `param0` instead of `customerId` and is of type `body` instead of `query` as it should be (see screenshot). Probably, Springfox should support the `@Param` annotation since that is the least intrusive annotation to define a parameter name in Spring Data repositories.

```java
@Api(tags = "Address Entity")
@RepositoryRestResource(path = "addresses")
public interface AddressRepository extends PagingAndSortingRepository<Address, Long> {

  @ApiOperation("find all Addresses that are associated with a given Customer")
  List<Address> findByCustomerId(@Param("customerId") Long customerId);

}
```

![param0](https://user-images.githubusercontent.com/1363578/28846494-f9891376-770b-11e7-800f-bd29dd92df09.png)

Workaround for this issue (see code below) is to annotate the parameter with `@RequestParam` to mark it as a query parameter and to override the name of the parameter using `@ApiParam` (can also be done with `@RequestParam` but you cannot define a description of the parameter then). But this workaround obviously relies on redundant information that may not reflect the actual API.

```java
@Api(tags = "Address Entity")
@RepositoryRestResource(path = "addresses")
public interface AddressRepository extends PagingAndSortingRepository<Address, Long> {

  @ApiOperation("find all Addresses that are associated with a given Customer")
  List<Address> findByCustomerId(@Param("customerId") @RequestParam @ApiParam(name="customerId", value="ID of the customer") Long customerId);
  
}
```

Working code containing this workaround: https://github.com/thombergs/code-examples/blob/master/spring-data-rest-springfox/src/main/java/com/example/demo/AddressRepository.java. Issue can be reproduced by removing the `@RequestParam` and `@ApiParam` annotations.

**Comment by dilipkrish** [comment]
Have you tried this snapshot build? I think this should be fixed

**Comment by thombergs** [comment]
Yep, works with 2.7.1-SNAPSHOT, thanks. Any idea when the 2.7.1 release will be coming?

**Comment by Chinna-SHS** [comment]
Hi,
Any idea about 2.7.1 release date? I am getting following error while use 2.7.1-SNAPSHOT version.

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: springfox.documentation.spring.web.WebMvcRequestHandler.<init>(Lorg/springframework/web/servlet/mvc/method/RequestMappingInfo;Lorg/springframework/web/method/HandlerMethod;)V
