### ISSUE TITLE
Snapshot 3.0.0 broken. @ConditionalOnClass did not find required class 

### ISSUE THREAD

**Issue by diykorey** [springfox/springfox#2929]
I use snapshot version 3.0.0
Seems on the latest update something went wrong.  Annotation parameter  on class Swagger2DocumentationWebMvcConfiguration point to class which is present only on older(release 2.9.2) version. It should be enough just change this line `@ConditionalOnClass(name = "springfox.documentation.spring.web.SpringfoxWebMvcConfiguration")` to `@ConditionalOnClass(name = "springfox.documentation.spring.web.SpringfoxWebConfiguration")` but honestly I didnt test such fix

Error on log

> 2019-03-07 10:47:33.001 [restartedMain] TRACE  [SpringBootCondition.java:92] - Condition OnClassCondition on springfox.documentation.swagger2.configuration.Swagger2DocumentationWebMvcConfiguration did not match due to @ConditionalOnClass did not find required class 'springfox.documentation.spring.web.SpringfoxWebMvcConfiguration' - org.springframework.boot.autoconfigure.condition.OnClassCondition

Info in MANIFEST.MF

> Manifest-Version: 1.0
> Implementation-Title: springfox-swagger2
> Built-With: gradle-5.2, groovy-2.5.4
> Implementation-Version: null
> Built-By: circleci
> Build-Time: 2019-02-26T02:07:09+0000
> Created-By: 1.8.0_181 (Oracle Corporation)
> Built-On: b17fd3680f46/172.23.0.3

![image](https://user-images.githubusercontent.com/3728938/53943974-09499e80-40c7-11e9-8043-0d70d1920e0f.png)

![image](https://user-images.githubusercontent.com/3728938/53943950-fd5ddc80-40c6-11e9-8acf-dc01117373c0.png)

**Comment by davidmelia** [comment]
I get the same and I'm not sure how 3.0.0 ever worked as Swagger2DocumentationWebMvcConfiguration checks for 
`@ConditionalOnClass(name = {"springfox.documentation.spring.web.SpringfoxWebMvcConfiguration"})`

but springfox.documentation.spring.web.SpringfoxWebMvcConfiguration only exists in springfox < 3.0.0.   Only springfox.documentation.spring.web.SpringfoxWebConfiguration exists but this is not checked.

**Comment by davidmelia** [comment]
Also Swagger2DocumentationWebMvcConfiguration import seems to be referencing another class which doesn't exist:

`import springfox.documentation.spring.web.WebMvcPropertySourcedRequestMappingHandlerMapping;`

**Comment by davidmelia** [comment]
Hi @diykorey 

I think your issue might be you need to include the dependency 

`
<dependency>
<groupId>io.springfox</groupId>
<artifactId>springfox-spring-webmvc</artifactId>
<version>3.0.0-SNAPSHOT</version>
</dependency>
`
into your project as spring fox 3 now supports flux and mvc.

This has fixed this issue for me.

Thanks

**Comment by diykorey** [comment]
Thx @davidmelia  
Unfortunately that jar doesn't consistent with 2.2.0 snapshot of springboot. Regards current issue I'm almost sure it's some regression on swagger snapshot, 'cause it worked for me before and then unexpectedly stopped

**Comment by burberius** [comment]
It works with Spring Boot 2.2.0 with the changes suggested in #2932.

**Comment by jahidakhtargit** [comment]
> Hi @diykorey
> 
> I think your issue might be you need to include the dependency
> 
> `<dependency> <groupId>io.springfox</groupId> <artifactId>springfox-spring-webmvc</artifactId> <version>3.0.0-SNAPSHOT</version> </dependency>`
> into your project as spring fox 3 now supports flux and mvc.
> 
> This has fixed this issue for me.
> 
> Thanks
Hi,
After adding the dependency I'm getting the below error:
Error: Unable to initialize main class 
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/servlet/LocaleResolver

**Comment by babjo** [comment]
Hi, @diykorey 
> I think your issue might be you need to include the dependency
```
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-spring-webmvc</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>
into your project as spring fox 3 now supports flux and mvc.
```

Thanks. Worked well.
