### ISSUE TITLE
logged errors: "NoSuchMethodError: Operation.<init>(…)" after upgrading to Springfox 3.0.0

### ISSUE THREAD

**Issue by bwaldvogel** [springfox/springfox#3451]
After upgrading Springfox from 2.9 to 3.0.0 I see a couple of logged errors when the Spring context is initialized. Note: The context seems to spin-up successfully despite the logged errors.

```
14:30:03.349 [Test worker] ERROR s.d.s.web.scanners.ApiDescriptionReader:87 #U#R#: Skipping process path[XYZ], method[XYZ] as it has an error.
java.lang.NoSuchMethodError: 'void springfox.documentation.service.Operation.<init>(org.springframework.http.HttpMethod, java.lang.String, java.lang.String, springfox.documentation.common.ExternalDocumentation, springfox.documentation.schema.ModelReference, java.lang.String, int, java.util.Set, java.util.Set, java.util.Set, java.util.Set, java.util.List, java.util.List, java.util.Set, java.lang.String, boolean, java.util.Collection, java.util.Set, springfox.documentation.service.RequestBody, java.util.Set)'
	at springfox.documentation.builders.OperationBuilder.build(OperationBuilder.java:376)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:146)
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:72)
	at springfox.documentation.spring.web.scanners.CachingOperationReader.lambda$new$0(CachingOperationReader.java:43)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1225)
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:48)
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:72)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:169)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67)
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.scanDocumentation(AbstractDocumentationPluginsBootstrapper.java:96)
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:82)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:100)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	[…]
```

I’m using using Spring Boot `2.3.2` with the following Springfox dependencies:
```
$ grep springfox gradle.lockfile

io.springfox:springfox-bean-validators:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-core:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-schema:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-spi:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-spring-web:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-spring-webflux:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-spring-webmvc:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-swagger-common:3.0.0=testCompileClasspath,testRuntimeClasspath
io.springfox:springfox-swagger2:3.0.0=testCompileClasspath,testRuntimeClasspath
```

**Comment by wangtao** [comment]
+1  same here

**Comment by wangtao** [comment]
well, I fixed it. 

I found it because I replaced Operation class in my project for parameter resorting. however the code is old.

**Comment by bwaldvogel** [comment]
Oh, I just realized that I had the workaround for https://github.com/springfox/springfox/issues/2705 in place which caused this problem :man_facepalming:.

Anyway, this might be helpful for others who encounter this issue and don’t realize they have a custom `springfox.documentation.service.Operation` in their codebase.

**Comment by dilipkrish** [comment]
Thank you for reporting back @bwaldvogel
