### ISSUE TITLE
Upgrading to springfox-boot-starter version 3 causes compilation errors in generated OpenAPIDocumentationConfig class

### ISSUE THREAD

**Issue by rcg0** [springfox/springfox#3554]
I must be missing something obvious when migrating to springfox-boot-starter version 3.

I have a small simple spring boot demo project, for generating server code based on an OpenAPI version 3 (OAS3) file. It is working with springfox-swagger2 version 2.9.2, but it generates OAS2 json file in api-docs (I would like OAS3). It's using the following dependencies:

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>

		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>

		
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>0.2.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

I am trying to upgrade to springfox-boot-starter version 3.0.0. Following the migration instructions, I removed the swagger2 dependency:

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>

		
		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>0.2.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

However, I am getting some issues:

- Generated class `OpenAPIDocumentationConfig` has a `@EnableSwagger2` annotation. As migration instructions tells to remove those, I didn't expect the generator to include it in the code. Generated classes shouldn't be edited manually.
- And the following compilation errors:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR
[INFO] -------------------------------------------------------------
[ERROR] .../generated-sources/openapi/src/main/java/poc/config/OpenAPIDocumentationConfig.java:[14,48] cannot find symbol
  symbol:   class RelativePathProvider
  location: package springfox.documentation.spring.web.paths
[ERROR] .../generated-sources/openapi/src/main/java/poc/config/OpenAPIDocumentationConfig.java:[50,53] cannot find symbol
  symbol:   class RelativePathProvider
  location: class es.fnmt.ceres.rest.autec.poc.config.OpenAPIDocumentationConfig
[ERROR] .../generated-sources/openapi/src/main/java/poc/config/OpenAPIDocumentationConfig.java:[44,31] incompatible types: es.fnmt.ceres.rest.autec.poc.config.OpenAPIDocumentationConfig.BasePathAwareRelativePathProvider cannot be converted to springfox.documentation.PathProvider
[ERROR] .../generated-sources/openapi/src/main/java/poc/config/OpenAPIDocumentationConfig.java:[58,9] method does not override or implement a method from a supertype
[ERROR] .../generated-sources/openapi/src/main/java/poc/config/OpenAPIDocumentationConfig.java:[60,91] cannot find symbol
  symbol: method applicationPath()
[ERROR] .../generated-sources/openapi/src/main/java/poc/config/OpenAPIDocumentationConfig.java:[63,9] method does not override or implement a method from a supertype
```

**Comment by yogi1817** [comment]
Any update on this?

**Comment by dilipkrish** [comment]
What is generating this source. You'd have to check with that library

**Comment by Pavankn18** [comment]
I am facing the same issue - was it resolved?

**Comment by billbarni** [comment]
Same issue here....

**Comment by ChillyWe** [comment]
Same issue here

**Comment by ashu17188** [comment]
same issue here

**Comment by clemjt** [comment]
same issue here
