### ISSUE TITLE
Swagger 3.0.0 not working with Spring 1.5.13.RELEASE

### ISSUE THREAD

**Issue by harshitdx29** [springfox/springfox#3512]
Hi,

I am using 

```
        <!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger-ui -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0</version>
        </dependency>
<!--         https://mvnrepository.com/artifact/io.springfox/springfox-swagger2-->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.mapstruct</groupId>
                    <artifactId>mapstruct</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But when I try to run the application: 

`org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;)Ljava/util/Optional;
`

I have also tried 2.10.5 but when I hit http://localhost:8080/swagger-ui.html. There is a pop up that it is not able to infer the base URL. 

For 2.9.2: 

`org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
`
Can you please help

**Comment by dilipkrish** [comment]
3.0.0 does not work with spring boot 2.2 and below. You'd have to use 2.9.2 unfortunately. In 2.9.2, ensure that your guava version matches the guava version brought in by 2.9.2

**Comment by harshitdx29** [comment]
yeah, manged to fix this. But not able to use default value/ example using ApiParam in a request param. Swagger UI always shows an empty field for that request param.

**Comment by nicolaskruger** [comment]
you are instaling spring fox 3 on the wrong way.
[doc](https://springfox.github.io/springfox/docs/snapshot/#migrating-from-existing-2-x-version)
