### ISSUE TITLE
update swagger 2.6.1 to 2.8.0 get Failed to start bean 'documentationPluginsBootstrapper' ApplicationContextException

### ISSUE THREAD

**Issue by chinadeng** [springfox/springfox#2435]
when i update swagger 2.6.1 to 2.8.0 get Failed to start bean 'documentationPluginsBootstrapper' ApplicationContextException; my swagger configure is like this:
@Configuration
@EnableSwagger2
@Profile("develop")
//@ComponentScan("com.ycnet.mirage.controller.FeeController")
public class Swagger2 {
	@Autowired
	private ServletContext servletContext;
	
	@Value("${server.port}")
	private String port;
	
	@Value("${server.context_path}")
	private String path;
	
	@Value("${spring.profiles.active}")
	private String profile;

	@Bean
	public Docket createRestApi() { return new Docket(DocumentationType.SWAGGER_2)  
			        .apiInfo(apiInfo())  
			        .select()  
			        .paths(PathSelectors.any())//如果是线上环境，添加路径过滤，设置为全部都不符合  
			        .build(); 
	}
	
	private ApiInfo apiInfo() {
		return new ApiInfoBuilder()
				.title("Zx接口文档")
				.description("请勿外传")
				.termsOfServiceUrl("Zx")
				.version("1.0")
				.build();
	}

Exception  stack:
Exception in thread "main" org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.web.bind.annotation.RequestMapping.path()[Ljava/lang/String;
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:142)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:648)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:909)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:898)
	at com.ycnet.mirage.MobileApplication.main(MobileApplication.java:119)
Caused by: java.lang.NoSuchMethodError: org.springframework.web.bind.annotation.RequestMapping.path()[Ljava/lang/String;
	at springfox.documentation.spring.web.scanners.ResourcePathProvider.paths(ResourcePathProvider.java:67)
	at springfox.documentation.spring.web.scanners.ResourcePathProvider$1.apply(ResourcePathProvider.java:50)
	at springfox.documentation.spring.web.scanners.ResourcePathProvider$1.apply(ResourcePathProvider.java:47)
	at com.google.common.base.Present.transform(Present.java:71)
	at springfox.documentation.spring.web.scanners.ResourcePathProvider.resourcePath(ResourcePathProvider.java:40)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:100)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:96)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	... 13 more

**Comment by georgelbf** [comment]
I'm also having this problem.

Occurs if the @RepositoryRestResource and JpaRepository are present together with @EnableSwagger2 @Import ({SpringDataRestConfiguration.class})

```
@RepositoryRestResource(collectionResourceRel = "customer", path = "customer")
public interface CustomerRestResource extends JpaRepository<Customer, Long> {
```

Spring Version: 2.0.2.RELEASE
Springfox Version: 2.9.1-SNAPSHOT


org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;

**Comment by dilipkrish** [comment]
@georgelbf Your error is different and is related to a breaking change in spring-data-rest. This library only supports pre spring boot 2.0.

@chinadeng Looks like a library problem. It says `java.lang.NoSuchMethodError: org.springframework.web.bind.annotation.RequestMapping.path()[Ljava/lang/String;` which is very odd. Are you using spring pre 4.2?

**Comment by cjoin** [comment]
You must use spring version at least 4.2.0.RELEASE.
This is the notes form org.springframework.web.bind.annotation.path():
/**
	 * In a Servlet environment only: the path mapping URIs (e.g. "/myPath.do").
	 * Ant-style path patterns are also supported (e.g. "/myPath/*.do").
	 * At the method level, relative paths (e.g. "edit.do") are supported within
	 * the primary mapping expressed at the type level. Path mapping URIs may
	 * contain placeholders (e.g. "/${connect}")
	 * <p><b>Supported at the type level as well as at the method level!</b>
	 * When used at the type level, all method-level mappings inherit
	 * this primary mapping, narrowing it for a specific handler method.
	 * @see org.springframework.web.bind.annotation.ValueConstants#DEFAULT_NONE
	 * @since 4.2
	 */
	@AliasFor("value")
	String[] path() default {};
